import React, { createContext, useContext, useState } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  it: {
    // Navigation
    'nav.services': 'Servizi',
    'nav.benefits': 'Vantaggi', 
    'nav.glamping': 'Glamping',
    'nav.projects': 'Progetti',
    'nav.contact': 'Contatti',
    
    // Hero Section
    'hero.title1': 'Costruzioni',
    'hero.title2': 'Sostenibili',
    'hero.subtitle': 'Realizziamo case prefabbricate innovative e parcheggi con fotovoltaico. Soluzioni eco-sostenibili per un futuro migliore.',
    'hero.cta1': 'Scopri i Nostri Progetti',
    'hero.cta2': 'Richiedi Preventivo',
    
    // Services
    'services.title': 'I Nostri Servizi',
    'services.subtitle': 'Soluzioni innovative per costruzioni sostenibili e produzione di energia rinnovabile',
    'services.prefab.title': 'Case Prefabbricate',
    'services.prefab.desc': 'Abitazioni moderne personalizzate, realizzate in poche settimane e montate in pochi giorni con materiali eco-sostenibili.',
    'services.prefab.feature1': 'Realizzazione in 3-4 settimane',
    'services.prefab.feature2': 'Montaggio in 2-3 giorni',
    'services.prefab.feature3': 'Materiali eco-compatibili',
    'services.prefab.feature4': 'Design personalizzabile',
    'services.parking.title': 'Parcheggi Fotovoltaici',
    'services.parking.desc': 'Strutture di parcheggio integrate con sistemi fotovoltaici per la produzione di energia pulita.',
    'services.parking.feature1': 'Produzione energia rinnovabile',
    'services.parking.feature2': 'Protezione veicoli',
    'services.parking.feature3': 'ROI garantito',
    'services.parking.feature4': 'Manutenzione minima',
    'services.button': 'Scopri di più',
    
    // Glamping
    'glamping.title': 'Glamping Eco-Luxury',
    'glamping.subtitle': 'Strutture glamping uniche che coniugano comfort e sostenibilità per esperienze indimenticabili',
    'glamping.feature1': 'Design eco-luxury personalizzato',
    'glamping.feature2': 'Installazione rapida',
    'glamping.feature3': 'Comfort alberghiero',
    'glamping.feature4': 'Impatto ambientale zero',
    'glamping.cta': 'Esplora le Soluzioni Glamping',
    
    // Benefits
    'benefits.title': 'Perché Scegliere le Nostre Soluzioni',
    'benefits.subtitle': 'Vantaggi concreti per il tuo investimento e per l\'ambiente',
    'benefits.eco.title': 'Eco-Sostenibile',
    'benefits.eco.desc': 'Materiali riciclabili e processi a basso impatto ambientale',
    'benefits.energy.title': 'Efficienza Energetica',
    'benefits.energy.desc': 'Sistemi avanzati per il risparmio energetico e la produzione di energia pulita',
    'benefits.speed.title': 'Tempi Ridotti',
    'benefits.speed.desc': 'Realizzazione in 3-4 settimane, montaggio in 2-3 giorni',
    'benefits.investment.title': 'Investimento Sicuro',
    'benefits.investment.desc': 'ROI garantito e riduzione dei costi operativi nel lungo termine',
    'benefits.maintenance.title': 'Manutenzione Minima',
    'benefits.maintenance.desc': 'Materiali durevoli e sistemi progettati per durare nel tempo',
    'benefits.smart.title': 'Tecnologia Smart',
    'benefits.smart.desc': 'Sistemi di monitoraggio e controllo intelligenti integrati',
    
    // Contact
    'contact.title': 'Contattaci',
    'contact.subtitle': 'Pronti a realizzare il tuo progetto sostenibile? Richiedi un preventivo gratuito',
    'contact.form.title': 'Richiedi Informazioni',
    'contact.form.name': 'Nome',
    'contact.form.surname': 'Cognome',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Telefono',
    'contact.form.service': 'Seleziona servizio di interesse',
    'contact.form.service.prefab': 'Case Prefabbricate',
    'contact.form.service.parking': 'Parcheggi Fotovoltaici',
    'contact.form.service.glamping': 'Glamping',
    'contact.form.service.all': 'Tutti i servizi',
    'contact.form.message': 'Descrivi il tuo progetto...',
    'contact.form.submit': 'Invia Richiesta',
    'contact.info.title': 'Informazioni di Contatto',
    'contact.info.address': 'Sede Operativa',
    'contact.info.phone': 'Telefono',
    'contact.info.email': 'Email',
    'contact.hours.title': 'Orari di Apertura',
    'contact.hours.weekdays': 'Lunedì - Venerdì',
    'contact.hours.saturday': 'Sabato',
    'contact.hours.sunday': 'Domenica',
    'contact.hours.closed': 'Chiuso',
    
    // Case Prefabbricate - Pagina Dedicata
    'prefab.characteristics.title': 'Caratteristiche delle nostre case',
    'prefab.characteristics.subtitle': 'Soluzioni di abitazione innovative che combinano design moderno, sostenibilità ambientale e tecnologie avanzate',
    'prefab.characteristics.speed.title': 'Tempi di costruzione rapidi',
    'prefab.characteristics.speed.desc': 'Produzione in fabbrica in 3-4 settimane, montaggio sul sito in soli 2-3 giorni. Efficienza e velocità senza compromettere la qualità.',
    'prefab.characteristics.materials.title': 'Materiali eco-sostenibili',
    'prefab.characteristics.materials.desc': 'Legname FSC certificato, isolamento naturale e materiali riciclabili. Costruzione a basso impatto ambientale.',
    'prefab.characteristics.design.title': 'Design personalizzabile',
    'prefab.characteristics.design.desc': 'Progetti personalizzati per ogni esigenza. Massima flessibilità nella progettazione dello spazio e delle finiture.',
    'prefab.characteristics.efficiency.title': 'Efficienza energetica',
    'prefab.characteristics.efficiency.desc': 'Classe energetica A4, sistemi di riscaldamento efficienti e possibilità di integrazione con pannelli fotovoltaici.',
    'prefab.characteristics.durability.title': 'Resistenza e durabilità',
    'prefab.characteristics.durability.desc': 'Strutture antiepide, antincendio e antigelo. Garanzie estese e manutenzione minima.',
    'prefab.characteristics.compliance.title': 'Normativa di regolamentazione',
    'prefab.characteristics.compliance.desc': 'Ottemperanza alle normative del Green Deal europeo, certificazioni CE e tutti gli standard di sicurezza.',
    'prefab.wheels.title': 'Case su ruote',
    'prefab.wheels.subtitle': 'Soluzioni innovative per case mobili e trasportabili, ideali per chi cerca flessibilità e libertà di movimento',
    'prefab.wheels.mobility.title': 'Massima mobilità',
    'prefab.wheels.mobility.desc': 'Case completamente trasportabili che ti permettono di cambiare posizione quando vuoi',
    'prefab.wheels.flexibility.title': 'Totale flessibilità',
    'prefab.wheels.flexibility.desc': 'Per siti temporanei, vacanze o progetti nomadi',
    'prefab.wheels.versatility.title': 'Versatilità d\'uso',
    'prefab.wheels.versatility.desc': 'Per case vacanza, uffici mobili o alloggi temporanei',
    'prefab.process.title': 'Il nostro processo di costruzione',
    'prefab.process.subtitle': 'Un approccio innovativo che garantisce una qualità superiore e tempi di consegna ridotti attraverso la prefabbricazione in ambiente controllato.',
    'prefab.process.step1.title': 'Progettazione personalizzata',
    'prefab.process.step1.desc': 'Sviluppiamo il progetto adattato alle tue specifiche esigenze',
    'prefab.process.step2.title': 'Produzione in fabbrica',
    'prefab.process.step2.desc': 'Costruzione in ambiente controllato per garantire precisione e qualità',
    'prefab.process.step3.title': 'Trasporto e montaggio',
    'prefab.process.step3.desc': 'Montaggio rapido sul sito in soli 2-3 giorni',
    'prefab.environment.title': 'Benefici ambientali',
    'prefab.environment.subtitle': 'Le nostre case prefabbricate contribuiscono agli obiettivi del Green Deal europeo per un futuro sostenibile',
    'prefab.environment.emissions.title': 'Riduzione delle emissioni',
    'prefab.environment.emissions.desc': 'Contribuiamo alla riduzione delle emissioni di gas serra del 55% entro il 2030, come richiesto dal Green Deal europeo.',
    'prefab.environment.emissions.point1': 'Materiali a basso impatto carbonico',
    'prefab.environment.emissions.point2': 'Processi di produzione ottimizzati',
    'prefab.environment.emissions.point3': 'Economia circolare dei materiali',
    'prefab.environment.standards.title': 'Standard zero emissioni',
    'prefab.environment.standards.desc': 'Tutte le nostre costruzioni sono progettate per essere zero emissioni entro il 2030, in linea con le normative europee.',
    'prefab.environment.standards.point1': 'Certificazione energetica A4',
    'prefab.environment.standards.point2': 'Integrazione di sistemi rinnovabili',
    'prefab.environment.standards.point3': '100% materiali riciclabili',
    'prefab.cta.title': 'Pronto a costruire la tua casa del futuro?',
    'prefab.cta.subtitle': 'Contattaci per una consulenza gratuita e scopri come possiamo costruire la tua casa dei sogni sostenibilmente e rapidamente.',
    'prefab.cta.button': 'Richiedi Preventivo',
    
    // Pannelli Solari - Pagina Dedicata
    'solar.solutions.title': 'Le nostre soluzioni fotovoltaiche',
    'solar.solutions.subtitle': 'Offriamo diverse configurazioni di parcheggio fotovoltaico per soddisfare ogni spazio e ogni esigenza di produzione di energia',
    'solar.solutions.double.title': 'Spazio per 2 auto',
    'solar.solutions.double.desc': 'Soluzione ottimale per 2 veicoli con massima produzione di energia',
    'solar.solutions.single.title': 'Spazio per 1 auto',
    'solar.solutions.single.desc': 'Soluzione compatta ideale per spazi piccoli e singolo veicolo',
    'solar.solutions.pergola.title': 'Pergola fotovoltaica',
    'solar.solutions.pergola.type': 'Residenziale',
    'solar.solutions.pergola.desc': 'Soluzione elegante per le terrazze e i giardini residenziali',
    'solar.solutions.specs.width': 'Larghezza',
    'solar.solutions.specs.depth': 'Profondità',
    'solar.solutions.specs.power': 'Potenza',
    'solar.solutions.specs.snow': 'Carico di neve',
    'solar.solutions.specs.wind': 'Carico di vento',
    'solar.solutions.specs.vehicles': 'Veicoli',
    'solar.solutions.specs.vehicles1': '1 auto',
    'solar.solutions.specs.vehicles2': '2 auto',
    'solar.solutions.pergola.specs.use': 'Uso',
    'solar.solutions.pergola.specs.useValue': 'Terrazza/Giardino',
    'solar.solutions.pergola.specs.dimensions': 'Dimensioni',
    'solar.solutions.pergola.specs.dimensionsValue': 'Personalizzabile',
    'solar.solutions.pergola.specs.style': 'Stile',
    'solar.solutions.pergola.specs.styleValue': 'Design moderno',
    'solar.solutions.features.highPower': 'Alta potenza',
    'solar.solutions.features.double': 'Spazio doppio',
    'solar.solutions.features.resistant': 'Resistente',
    'solar.solutions.features.compact': 'Compatto',
    'solar.solutions.features.efficient': 'Efficiente',
    'solar.solutions.features.versatile': 'Versatile',
    'solar.solutions.pergola.features.residential': 'Residenziale',
    'solar.solutions.pergola.features.design': 'Design',
    'solar.solutions.pergola.features.customizable': 'Personalizzabile',
    'solar.veranda.title': 'Veranda con fotovoltaico',
    'solar.veranda.subtitle': 'Spazi di vita all\'aperto che producono energia pulita, perfetti per godersi la natura con tutti i comfort',
    'solar.veranda.living.title': 'Spazio di vita',
    'solar.veranda.living.desc': 'Terrazze coperti ideali per cene all\'aperto, relax e divertimento',
    'solar.veranda.outdoor.title': 'Vita all\'aperto',
    'solar.veranda.outdoor.desc': 'Protezione dalle intemperie mantenendo il contatto con la natura',
    'solar.veranda.comfort.title': 'Comfort garantito',
    'solar.veranda.comfort.desc': 'Sistemi di illuminazione e ventilazione integrati per massimo comfort',
    'solar.benefits.title': 'Benefici del nostro parcheggio fotovoltaico',
    'solar.benefits.subtitle': 'Una soluzione intelligente che combina protezione veicoli e produzione di energia pulita',
    'solar.benefits.energy.title': 'Produzione di energia',
    'solar.benefits.energy.desc': 'Genera energia pulita per alimentare le tue attività, riducendo i costi della bolletta elettrica fino al 70%.',
    'solar.benefits.protection.title': 'Protezione veicoli',
    'solar.benefits.protection.desc': 'Protegge i veicoli dalle intemperie, pioggia, raggi UV e altri agenti atmosferici, preservando il loro valore.',
    'solar.benefits.roi.title': 'ROI garantito',
    'solar.benefits.roi.desc': 'Ritorno sull\'investimento garantito in 8-10 anni attraverso le vendite di energia e incentivi governativi.',
    'solar.benefits.environment.title': 'Impatto ambientale',
    'solar.benefits.environment.desc': 'Contribuisce alla riduzione delle emissioni di CO2 e supporta gli obiettivi del Green Deal europeo.',
    'solar.benefits.savings.title': 'Risparmio economico',
    'solar.benefits.savings.desc': 'Riduzione significativa delle bollette elettriche e protezione dall\'aumento dei prezzi dell\'energia.',
    'solar.benefits.warranty.title': 'Garanzia estesa',
    'solar.benefits.warranty.desc': 'Garanzia di 25 anni sui pannelli e di 10 anni sui componenti elettronici per massima tranquillità.',
    'solar.cta.title': 'Inizia a produrre energia pulita oggi',
    'solar.cta.subtitle': 'Trasforma il tuo parcheggio in una fonte di energia rinnovabile. Contattaci per un\'analisi di fattibilità gratuita.',
    'solar.cta.button1': 'Richiedi Preventivo',
    'solar.cta.button2': 'Calcola il tuo ROI',
    
    // Glamping - Pagina Dedicata
    'glamping.solutions.title': 'Le nostre soluzioni glamping',
    'glamping.solutions.subtitle': 'Strutture innovative che rivoluzionano il concetto di ristorazione all\'aperto, combinando lusso e sostenibilità',
    'glamping.solutions.pod.title': 'Pod glamping eco-luxe',
    'glamping.solutions.pod.desc': 'Strutture compatte e autosufficienti, perfette per coppie o piccoli gruppi. Design moderno con tutti i comfort di un hotel di lusso.',
    'glamping.solutions.suite.title': 'Suite Resort',
    'glamping.solutions.suite.desc': 'Soluzioni spaziose per famiglie o gruppi, con aree separate per massimo comfort e privacy. Ideale per soggiorni prolungati.',
    'glamping.solutions.specs.surface': 'Superficie',
    'glamping.solutions.specs.guests': 'Ospiti',
    'glamping.solutions.specs.guests2': '2-4 persone',
    'glamping.solutions.specs.guests4': '4-6 persone',
    'glamping.solutions.specs.bathroom': 'Bagno',
    'glamping.solutions.specs.bathroomValue': 'Completo privato',
    'glamping.solutions.specs.kitchen': 'Cucina',
    'glamping.solutions.specs.kitchenValue': 'Angolo cucina',
    'glamping.solutions.specs.kitchenComplete': 'Completo',
    'glamping.solutions.specs.climate': 'Clima',
    'glamping.solutions.specs.climateValue': 'Condizionamento',
    'glamping.solutions.specs.terrace': 'Terrazza',
    'glamping.solutions.specs.terraceValue': '15 m² privata',
    'glamping.solutions.specs.terracePanoramic': '25 m² panoramica',
    'glamping.solutions.specs.rooms': 'Stanze',
    'glamping.solutions.specs.roomsValue': '2 separate',
    'glamping.solutions.specs.living': 'Soggiorno',
    'glamping.solutions.specs.livingValue': 'Area dedicata',
    'glamping.features.title': 'Caratteristiche premium',
    'glamping.features.subtitle': 'Ogni struttura è progettata per offrire un\'esperienza unica che supera le aspettative dei più esigenti ospiti',
    'glamping.features.sustainable.title': 'Design sostenibile',
    'glamping.features.sustainable.desc': 'Materiali naturali, sistemi di ventilazione passiva e isolamento eco-compatibile per massimo comfort rispettando l\'ambiente.',
    'glamping.features.comfort.title': 'Comfort alberghiero',
    'glamping.features.comfort.desc': 'Tessuti di alta qualità, minibar, Wi-Fi, condizionamento, e tutti i servizi previsti da un hotel 5 stelle.',
    'glamping.features.energy.title': 'Energia autonoma',
    'glamping.features.energy.desc': 'Sistemi fotovoltaici integrati e batterie di stoccaggio per l\'energia completa indipendenza e impatto zero ambientale.',
    'glamping.features.installation.title': 'Installazione rapida',
    'glamping.features.installation.desc': 'Montaggio in 1-2 giorni con impatto minimo sul territorio. Strutture modulari facilmente trasportabili e riposizionabili.',
    'glamping.features.experience.title': 'Esperienza unica',
    'glamping.features.experience.desc': 'Finestre panoramiche grandi, terrazze private e design che si integra perfettamente con il paesaggio naturale circostante.',
    'glamping.features.safety.title': 'Sicurezza certificata',
    'glamping.features.safety.desc': 'Strutture certificate per resistenza sismica, antincendio e conformi a tutte le normative di sicurezza per strutture di ristorazione.',
    'glamping.roi.title': 'Un investimento che paga',
    'glamping.roi.subtitle': 'Il glamping è uno dei settori più in rapida crescita nel turismo, con tariffe premium e alte occupazioni durante l\'anno.',
    'glamping.roi.premium.title': 'Tariffe premium',
    'glamping.roi.premium.desc': 'Prezzi medi 30-50% più alti rispetto ai campeggi tradizionali con margini di profitto elevati',
    'glamping.roi.occupancy.title': 'Occupazione elevata',
    'glamping.roi.occupancy.desc': 'Occupazione media del 75-85% con picchi fino al 95% in alta stagione',
    'glamping.roi.return.title': 'ROI 8-12 anni',
    'glamping.roi.return.desc': 'Ritorno sull\'investimento garantito in 8-12 anni con crescita regolare dei ricavi',
    'glamping.roi.advantages.title': 'Vantaggi competitivi',
  },
  en: {
    // Navigation
    'nav.services': 'Services',
    'nav.benefits': 'Benefits',
    'nav.glamping': 'Glamping',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title1': 'Sustainable',
    'hero.title2': 'Construction',
    'hero.subtitle': 'We create innovative prefabricated houses and photovoltaic parking structures. Eco-sustainable solutions for a better future.',
    'hero.cta1': 'Discover Our Projects',
    'hero.cta2': 'Request Quote',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Innovative solutions for sustainable construction and renewable energy production',
    'services.prefab.title': 'Prefabricated Houses',
    'services.prefab.desc': 'Custom modern homes, built in just a few weeks and assembled in just a few days with eco-sustainable materials.',
    'services.prefab.feature1': 'Built in 3-4 weeks',
    'services.prefab.feature2': 'Assembled in 2-3 days',
    'services.prefab.feature3': 'Eco-compatible materials',
    'services.prefab.feature4': 'Customizable design',
    'services.parking.title': 'Photovoltaic Parking',
    'services.parking.desc': 'Parking structures integrated with photovoltaic systems for clean energy production.',
    'services.parking.feature1': 'Renewable energy production',
    'services.parking.feature2': 'Vehicle protection',
    'services.parking.feature3': 'Guaranteed ROI',
    'services.parking.feature4': 'Minimal maintenance',
    'services.button': 'Learn more',
    
    // Glamping
    'glamping.title': 'Eco-Luxury Glamping',
    'glamping.subtitle': 'Unique glamping structures that combine comfort and sustainability for unforgettable experiences',
    'glamping.feature1': 'Custom eco-luxury design',
    'glamping.feature2': 'Quick installation',
    'glamping.feature3': 'Hotel-level comfort',
    'glamping.feature4': 'Zero environmental impact',
    'glamping.cta': 'Explore Glamping Solutions',
    
    // Benefits
    'benefits.title': 'Why Choose Our Solutions',
    'benefits.subtitle': 'Concrete benefits for your investment and the environment',
    'benefits.eco.title': 'Eco-Sustainable',
    'benefits.eco.desc': 'Recyclable materials and low environmental impact processes',
    'benefits.energy.title': 'Energy Efficiency',
    'benefits.energy.desc': 'Advanced systems for energy saving and clean energy production',
    'benefits.speed.title': 'Reduced Time',
    'benefits.speed.desc': 'Built in 3-4 weeks, assembled in 2-3 days',
    'benefits.investment.title': 'Safe Investment',
    'benefits.investment.desc': 'Guaranteed ROI and reduced operating costs in the long term',
    'benefits.maintenance.title': 'Minimal Maintenance',
    'benefits.maintenance.desc': 'Durable materials and systems designed to last over time',
    'benefits.smart.title': 'Smart Technology',
    'benefits.smart.desc': 'Integrated intelligent monitoring and control systems',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Ready to realize your sustainable project? Request a free quote',
    'contact.form.title': 'Request Information',
    'contact.form.name': 'First Name',
    'contact.form.surname': 'Last Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.service': 'Select service of interest',
    'contact.form.service.prefab': 'Prefabricated Houses',
    'contact.form.service.parking': 'Photovoltaic Parking',
    'contact.form.service.glamping': 'Glamping',
    'contact.form.service.all': 'All services',
    'contact.form.message': 'Describe your project...',
    'contact.form.submit': 'Send Request',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Headquarters',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.hours.title': 'Opening Hours',
    'contact.hours.weekdays': 'Monday - Friday',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.closed': 'Closed',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['it']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}